spring:
  datasource:
    url: jdbc:mysql://118.67.131.174:3306/batch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: batch_test
    password: batchTest@123
    hikari:
      maximum-pool-size: 3
      connection-timeout: 50000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 3
      idle-timeout: 600000
      max-lifetime: 1800000
# job 이름으로 구분하여 실행하기 위한 설정
  batch:
    job:
      enabled: true
      
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
